#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/autostart.sh
#xsetroot -cursor_name left_ptr &

#bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor eDP-1-0 -s HDMI-0

bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config single_monocle              false
bspc config focused_border_color        "#49c49a"
bspc config normal_border_color         "#808080"
bspc config focus_follows_pointer       true

bspc rule -a firefox desktop='^1'
bspc rule -a Steam desktop='^2'
bspc rule -a ryzen-controller desktop='^6'
bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a PureRef state=floating
bspc rule -a steam_app_1172470 desktop=^2 state=fullscreen
bspc rule -a feh state=fullscreen
